config/routes.rb
SampleApp::Application.routes.draw do
  resources :users

  get "users/new"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/signup',  :to => 'users#new'
  match '/users',   :to => 'users#show'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"

   root :to => 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, 	:presence 	=> 	 true,
  									:length 		=> { :minimun => 3, :maximum => 50 }
  validates :email, :presence 	=> 	 true,
  									:format 		=> { :with => email_regex },
  									:uniqueness	=> { :case_sensitive => false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Principal"
  end

  def contact
  	@title = "Contacto"
  end

  def about
  	@title = "Sobre nosotros"
  end
  
  def help 
  	@title = "Ayuda"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@title = "Sign up"
  end

  def show
  	@user = User.find(params[:id])
  end

  def index
  	@user = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	#Regresa un valor para el titulo
	def title
		base_title = "Ruby on Rails"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top">		
	<div class="navbar-inner">
		<div class="container">
			<span class="brand">Pruebas ROR</span>
			<ul class="nav">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Sign in", signup_path %></li>
			</ul>
		</div>
	</div>		
<ul class="breadcrumb subnav">
	  <li> <%= title %></li>		  
  </ul>
</nav>

app/views/layouts/_stylesheets.html.erb
<!-- [if lt IE9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif] -->	
  <!-- [if lt IE8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= javascript_include_tag 	"application" %>
  <%= javascript_include_tag 	"bootstrap-dropdown" %>
  <%= stylesheet_link_tag			"css/bootstrap", :media => "screen" %>
  <%= stylesheet_link_tag			"custom", :media => "screen" %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tags %>
  <%= render "layouts/stylesheets" %>  
</head>
<body>
	<%= render "layouts/header" %>	
	<section class="container">					
		<div class="hero-unit">
			<%= debug(params) if Rails.env.development? %>	
		</div>			
		<div class="container-fluid">
			<%= yield %>
		</div>					
		</footer>	
	</section>		
	<footer>		
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/abouthtml.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to "Sign up", signup_path, :class => "btn btn-primary btn-large" %>

app/views/users/index.html.erb
<% 
	@user.each do |usuario| 
%>
	<div class="row-fluid">
		<div class="span6">
			<%= usuario.name %> 
		</div>
		<div class="span4 offset2">
			<div class="btn-group">
			    <%= link_to "Mas info", (users_path + "/#{usuario.id}"), :class => 'btn' %> </button>
			    <button class="btn">Modificar</button>
			    <button class="btn">Eliminar</button>
		    </div>
			
		</div>
	</div>
<%
	end
%>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div>
	<%= @user.name %> <%= @user.email %>	
</div>